4_Week/2_Session/ModelFun/Models/ErrorViewModel.cs
using System;

namespace ModelFun.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

4_Week/2_Session/ModelFun/Models/Friend.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace ModelFun.Models
{
    public class Friend
    {
        [Required(ErrorMessage="CUSTOM THING EHERE")]
        [MinLength(3)]
        [MaxLength(20)]
        public string NickName {get;set;}
        [Required]
        [DataType(DataType.Date)]
        public DateTime DOB {get;set;}
        [Required]
        [Range(0, 20, ErrorMessage="NUM HANDS must be normal")]
        public int NumHands {get;set;}
        
    }
    public class WeirdModelThing
    {
        public Friend BestFriend {get;set;}
        public Friend NewFriend {get;set;}
        public Friend[] MyFriends {get;set;}
        public bool HasPizza {get;set;}
    }
}

4_Week/2_Session/ModelFun/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ModelFun.Models;

namespace ModelFun.Controllers
{
    public class FriendController : Controller
    {
        [HttpGet("")]
        public IActionResult Index()
        {
           
            return View();
        }
       
        [HttpPost("create")]
        public IActionResult Create(Friend newFriend)
        {
            if(ModelState.IsValid)
            {
                return RedirectToAction("SomewhereCool");
            }
            return View("Index");

        }
        [HttpGet("SOMEWHERECOOL")]
        public string SomewhereCool()
        {
            return "SO COOL HERE GUYS!";
        }
    }
}

4_Week/2_Session/ModelFun/Views/Friend/Index.cshtml
@{
    ViewData["Title"] = "Welcome Page";
}
@model Friend

<form asp-action="Create" asp-controller="Friend" method="POST">
    <div class="form-group">
        <span asp-validation-for="NickName"></span>
        <label asp-for="NickName"></label>
        <input asp-for="NickName">
    </div>
    <div class="form-group">
        <span asp-validation-for="DOB"></span>
        <label asp-for="DOB"></label>
        <input asp-for="DOB">
    </div>
    <div class="form-group">
        <span asp-validation-for="NumHands"></span>
        <label asp-for="NumHands"></label>
        <input asp-for="NumHands">
    </div>
    <button>DO IT</button>
</form>

4_Week/2_Session/ModelFun/Views/Friend/RegView.cshtml
@model Friend
<h1>Hello @Model, sign up now!</h1>

<form asp-action="Create" asp-controller="Home" method="POST">
    <div class="form-group">
        <label asp-for="Nombre"></label>
        <input asp-for="Nombre">
    </div>
    <div class="form-group">
        <label asp-for="NumHands"></label>
        <input asp-for="NumHands">
    </div>
    <div class="form-group">
        <span asp-validation-for="Age"></span>
        <label asp-for="Age"></label>
        <input asp-for="Age">
    </div>
    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title">
    </div>
    <button>SEND IT</button>
</form>
<span asp-validation-for="NumHands"></span>
<span asp-validation-for="Nombre"></span>
<span asp-validation-for="Title"></span>